name: Build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: make lint

  build_docker_image_pr:
    name: Build Docker Image for PR
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          load: true # Ensure image is loaded into local Docker daemon
          tags: pylon-test-image:latest # Tag for local testing

      - name: Test ARM64 Docker Image
        run: |
          echo "Attempting to run the ARM64 image..."
          # This command will fail if pylon binary has issues like the syntax error
          docker run --rm --platform linux/arm64 pylon-test-image:latest /usr/local/bin/pylon
          echo "ARM64 image run attempt finished."
